# Generated by Django 4.0.3 on 2022-03-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_indicadormodel_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicadormodel',
            name='tipo',
        ),
    ]
