# Generated by Django 4.0.3 on 2022-03-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_remove_indicadormodel_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadormodel',
            name='tipo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
