# Generated by Django 4.0.3 on 2022-03-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=70)),
                ('categoria', models.CharField(max_length=70)),
                ('subcategoria', models.CharField(max_length=70)),
            ],
        ),
    ]
