# Generated by Django 4.0.3 on 2022-03-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='clasificacion',
        ),
    ]
